= Adding External `Prometheus` for a `Service Mesh` via `prometheus-operator`

These instructions describe one of the options to setup `Prometheus` for a production setup for the `SMCP` previously installed and relies on such a resource to be available.

WARNING: These instructions rely on the version of Openshift as they will utilize the same `Prometheus Operator` CRDs as they are installed in the `openshift-monitoring` namespace.

* *Prerequisite:* `helm` binary version 3 is required to be in the path
* *Prerequisite:* `sed`  binary is required to be in the path

NOTE: The following instructions offer a step-by-step description on the configurations that need to be applied and actions required following these configurations. Having read through and applied the configurations you can login as `Cluster Admin` and execute the one step script `update-prod-smcp-2-option2-prometheus.sh prod-istio-system production https://prometheus-prod-istio-system.apps.cluster-94qkd.94qkd.sandbox1628.opentlc.com/`

[NOTE]
====
Actions with role `Cluster Admin`
====

1. The `ServiceMeshControlPlane` is deployed and it is in `Ready` state and it has `Prometheus Addon` enabled.
+
----
./login-as.sh phillip
oc project prod-istio-system
oc -n prod-istio-system get smcp
----
2. Scale down the Deployment of `Prometheus`. The ServiceMesh operator will not reconcile the replicas.
+
----
./login-as.sh phillip
oc -n prod-istio-system scale --replicas=0 deployment/prometheus
----

3. Configure and Deploy the prometheus operator
* link:./prometheus-resources/values.yaml[/prometheus-resources/values.yaml] require to be reviewied as follows:
** `prometheusOperator.image.repository` and `prometheusOperator.image.tag` will have to match the Openshift cluster version (eg. https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.10.24/release.txt)
+
----
./login-as.sh phillip
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm repo list
helm upgrade --debug --install production  prometheus-community/kube-prometheus-stack -f values.yaml --skip-crds
oc -n prod-istio-system get prometheus
----

4. Prepare to apply the same -as `SMCP`- prometheus configuration:
* Extract the `ConfigMap` based prometheus configurations (only the list of `job_name`, see link:https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md[Additional Scrape Configuration]) into a `Secret`
+
----
./login-as.sh phillip
oc get cm prometheus -o jsonpath="{.data.prometheus\.yml}" > ./prometheus-resources/prometheus-additional.yaml
sed -i '1,/scrape_configs:/d' prometheus-additional.yaml
oc -n prod-istio-system create secret generic additional-scrape-configs --from-file=./prometheus-resources/prometheus-additional.yaml
----

5. Edit the dedicated `prometheus-<smcp-namespace>` clusterrole to allow `tokenreviews` and `subjectaccessreviews`.
+
----
./login-as.sh phillip
oc get clusterrole prometheus-prod-istio-system -o jsonpath='{.rules}'
oc apply -f <(cat <(oc get clusterrole prometheus-prod-istio-system -o yaml) ./prometheus-resources/prometheus-clusterrole-patch.yaml)
oc get clusterrole prometheus-prod-istio-system -o jsonpath='{.rules}'
----

6. Create a `ClusterRoleBinding` for the `prometheus` serviceaccount to the `prometheus-<smcp-namespace> ClusterRole  (The existing SMCP created `RoleBinding` does not work with the Prometheus operator base installation).
+
----
./login-as.sh phillip
"apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prod-istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: istio
    maistra.io/owner: prod-istio-system
    maistra.io/owner-name: basic
  name: prometheus-prod-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-prod-istio-system
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prod-istio-system"| oc apply -n prod-istio-system -f -
----

7. Configure and Deploy the link:./prometheus-resources/prometheus-cr.yaml[`Prometheus` CR] as follows:

* The CR must reuse the same `secrets`, `configMap` and `ServiceAccount` as the one generated by ServiceMesh (see contents in the provided link:./prometheus-resources/prometheus-cr.yaml[`Prometheus` CR] File).
** `configMap` starting `istio-xxx` should be the name of `istio-<tenant-name>`.
* The port definition must be the same as the one provided by the ServiceMesh.
* The `args` for the `prometheus` container must be compared to the ones applied in the `Prometheus` resource in `openshift-monitoring` and if necessary updated in the provided link:./prometheus-resources/prometheus-cr.yaml[`Prometheus` CR] File.
* Apply the same -as `SMCP`- prometheus configuration by adding `additionalScrapeConfigs` in the CR pointing to the `Secret` created above (`additional-scrape-configs`) and key `additional-scrape-configs.yaml`.
* `externalUrl`: should match the `Route` URL generated by the `SMCP` deployment earlier.
* `image`: for each of the 3 containers (`prometheus-proxy`, `prometheus`, `config-loader`) must match the SHA of the openshift release you are deploying in (see example link:https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.10.24/release.txt[4.10.24 Openshift Release])
* `maistra.io/member-of`: must contain the `controlplane` namespace name
* `app.kubernetes.io/part-of`: must contain the `controlplane` namespace name
* `app.kubernetes.io/version`, `version`: is good practice to contain the same version as for `prometheus-k8s` in `openshift-monitoring` as it would indicate the prometheus version deployed by the operator.
* `spec.storage`: section to be reviewed and appropriate `StorageClass` information (`oc get storageclass`) , PV size to be set.
+
----
./login-as.sh phillip
oc -n prod-istio-system apply -f ./prometheus-resources/prometheus-cr.yaml
oc -n prod-istio-system get statefulset
----

* For clean up
** delete the `Prometheus` resource
** check that the PVCs (eg. prometheus-prometheus-db-prometheus-prometheus-0, prometheus-prometheus-db-prometheus-prometheus-1)  have been removed, if not delete them
** remove the `prometheus-operator` release (`helm uninstall production`)
** scale back up the `prometheus` deployment created by SMCP.